// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhK403Faxgsg63fxuzJ6RpM6PYvZ3HqP0',
    appId: '1:547968083198:web:777585cd3a25615ec2b1af',
    messagingSenderId: '547968083198',
    projectId: 'ict602-carrymark-570ec',
    authDomain: 'ict602-carrymark-570ec.firebaseapp.com',
    storageBucket: 'ict602-carrymark-570ec.firebasestorage.app',
    measurementId: 'G-WSC1R79JYZ',
    databaseURL: 'https://ict602-carrymark-570ec-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDosxscIfkoGmT4AH-3tz0KPAshRlL1Zzc',
    appId: '1:547968083198:android:c2aadc3fa1a7cd5ec2b1af',
    messagingSenderId: '547968083198',
    projectId: 'ict602-carrymark-570ec',
    storageBucket: 'ict602-carrymark-570ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrmLOjkSmk7--x7tEDzYgK4xv8YtqccOU',
    appId: '1:547968083198:ios:45d7b43371e47a3fc2b1af',
    messagingSenderId: '547968083198',
    projectId: 'ict602-carrymark-570ec',
    storageBucket: 'ict602-carrymark-570ec.firebasestorage.app',
    iosBundleId: 'com.example.ict602CarrymarkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrmLOjkSmk7--x7tEDzYgK4xv8YtqccOU',
    appId: '1:547968083198:ios:45d7b43371e47a3fc2b1af',
    messagingSenderId: '547968083198',
    projectId: 'ict602-carrymark-570ec',
    storageBucket: 'ict602-carrymark-570ec.firebasestorage.app',
    iosBundleId: 'com.example.ict602CarrymarkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhK403Faxgsg63fxuzJ6RpM6PYvZ3HqP0',
    appId: '1:547968083198:web:a1955509f0099092c2b1af',
    messagingSenderId: '547968083198',
    projectId: 'ict602-carrymark-570ec',
    authDomain: 'ict602-carrymark-570ec.firebaseapp.com',
    storageBucket: 'ict602-carrymark-570ec.firebasestorage.app',
    measurementId: 'G-H43Q7J66BB',
  );
}
